### ISSUE TITLE
Release sentinelsat on conda-forge

### ISSUE THREAD

**Issue by bilelomrani1** [sentinelsat/sentinelsat#399]
I use `sentinelsat` alongside some packages that wrap an external library (`gdal`, `geopandas`,...). For these, it's really convenient to install them with `conda` and the `conda-forge` channel. `sentinesat` is not released on `conda-forge` and thus difficult to update/manage using `conda`. Is there any plan to make the package accessible from `conda`?

**Comment by j08lue** [comment]
You know you can include `pip` packages in `conda` `environment.yml` files, right?

```yaml
name: eo
dependencies:
- python>=3.6
- geopandas
- gdal
- pip
- pip:
  - sentinelsat
```

I wonder whether this pain point otherwise is large enough to warrant us maintaining packages several places...

**Comment by bilelomrani1** [comment]
I was aware of this, but I was rather looking at a way to specify a `requirement.txt` that can be read by `conda`. The only downside is that all packages have to be managable by `conda`. But I understand that it may not be worth the effort, it's okay, I guess I can install one dependency using `pip` on top.

**Comment by j08lue** [comment]
Cool. You probably know this, but just because you mentioned [`requirements.txt`]([this](https://stackoverflow.com/a/59056234)):

```yaml
name: eo
dependencies:
- python>=3.6
- pip
- pip:
  - -r file:requirements.txt
```
